### ISSUE TITLE
SDK crash

### ISSUE THREAD

**Issue by oscdan** [iovation/deviceprint-SDK-Android#3]
iovation sdk is crashing and Strict Mode detects it

```
2019-07-30 17:57:34.693 27774-27786 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.io.FileInputStream.<init>(FileInputStream.java:151)
        at android.app.ContextImpl.openFileInput(ContextImpl.java:527)
        at android.content.ContextWrapper.openFileInput(ContextWrapper.java:195)
        at com.iovation.mobile.android.details.u.a(Unknown Source:9)
        at com.iovation.mobile.android.details.u.a(Unknown Source:0)
        at com.iovation.mobile.android.details.i.a(Unknown Source:31)
        at com.iovation.mobile.android.FraudForceManager.a(Unknown Source:0)
        at com.iovation.mobile.android.FraudForceManager.getBlackbox(Unknown Source:31)
```

**Comment by ashley-campbell-iovation** [comment]
Thank you for the feedback. Please contact your Integration Engineer resolve this issue.

**Comment by DmitrijsD** [comment]
Having same issue here with 4.2.0 version
