### ISSUE TITLE
Android API 30: java.lang.SecurityException: getDataNetworkTypeForSubscriber

### ISSUE THREAD

**Issue by ilyinSV** [iovation/deviceprint-SDK-Android#7]
iovation SDK version : 4.2.0

compileSdkVersion 30

W/System.err: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.iovation.mobile.android.b.o.b(:20)
        at com.iovation.mobile.android.b.i.a(Unknown Source:31)
        at com.iovation.mobile.android.FraudForceManager.getBlackbox(:6)

**Comment by aenglander** [comment]
If you need immediate assistance, please contact you integration specialist or customer success manager. Otherwise, it may take over a week to receive a response via GitHub issues at this time.

**Comment by ashley-campbell-iovation** [comment]
Hello! 

I'm curious if this issue was ever resolved. I believe we have reproduced this issue and there will be a fix coming in our next update later this month.

Thanks!
Ashley

**Comment by ashley-campbell-iovation** [comment]
This issue should be resolved in v4.3.0.
